<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>9cc53503-bd1e-4405-b223-f2b90d3fce59</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="8.0.0"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="8.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UserService.API\UserService.API.csproj" />
      <ProjectReference Include="..\UserService.Infrastructure\UserService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
